- name: Run a Kafka Producer
  shell:
    chdir: /vagrant/src
    # Create a Kafka producer. Use first EC2 instance as bootstrap server. 2nd as data sink.
    cmd: "python3 driver.py -v -p -pa VagrantAnsibleProducer -n 20 -t stock-market-data -ss AMZN  --bootstrap_server {{ hostvars['127.0.0.1'].ec2_1.instances[0].public_ip_address }} --data_sink_server {{ hostvars['127.0.0.1'].ec2_2.instances[0].public_ip_address }} > producer.log"
  async: 600 # allow 10 minutes
  poll: 0
  register: producer


  # Manual Producer Command:
  # python3 driver.py -v -p -pa AustinProducer -n 20 -t stock-market-data -ss AMZN  --bootstrap_server 3.94.206.118  --data_sink_server 3.86.109.168