## Tasks that provision a CouchDB host
- name: Install curl, apt-transport-https, gnupg
  apt:
    update_cache: yes
    name: '{{ item }}'
    state: present
  loop:
  - curl
  - apt-transport-https
  - gnupg

- name: Curl CouchDB
  shell: curl https://couchdb.apache.org/repo/keys.asc | gpg --dearmor | sudo tee /usr/share/keyrings/couchdb-archive-keyring.gpg >/dev/null 2>&1

- name: Update apt sources with couchdb
  shell: >
    . /etc/os-release && \
    echo "deb [signed-by=/usr/share/keyrings/couchdb-archive-keyring.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/ ${VERSION_CODENAME} main" \
    | sudo tee /etc/apt/sources.list.d/couchdb.list >/dev/null

- name: Install CouchDB
  apt:
    name: couchdb
    update_cache: yes

- name: Set couchdb bind chttpd bind address to 0.0.0.0
  lineinfile:
    path: /home/kafka/kafka/config/server.properties
    regexp: 'bind_address.*'
    line: bind_address = 0.0.0.0