# ZOOKEEPER SERVICES - DEPEND ON zookeeper-deployment
# Service objects for exposing the deployments corresponding to the selectors
---
# If you are inside of the cluster, access a service with cluster DNS name of: service_name.service_namespace.svc.cluster.local
# ClusterIP service for accessing zookeeper from within cluster
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    app: zookeeper
  ports:
    # Client connections to zookeeper
    - protocol: TCP
      port: 2181
      targetPort: 2181
      name: client
---
# Headless clusterIP service for zookeeper
# Great explanation for this decision can be found here: https://stackoverflow.com/questions/52707840/what-is-a-headless-service-what-does-it-do-accomplish-and-what-are-some-legiti
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless-service
spec:
  selector:
    app: zookeeper
  clusterIP: None # headless service
  ports:
    # used by ZK peers to talk to each other
    - protocol: TCP
      port: 2888
      targetPort: 2888
      name: server
    # used by ZK peers to talk to each other
    - protocol: TCP
      port: 3888
      targetPort: 3888
      name: leader-election

# END ZOOKEEPER SERVICES - DEPEND ON zookeeper-deployment

---
### Expose kafka cluster internally for brokers to self-reference and
### for consumer to use for bootstrap
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-internal
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      name: broker0
---
# Expose Kafka cluster externally for producers to connect
apiVersion: v1
kind: Service
metadata:
  name: kafka-service-external
spec:
  type: NodePort
  selector:
    app: kafka
    brokerId: "0"
  ports:
    # External client connections to Kafka bootstrap node
    - name: bootstrap
      protocol: TCP
      port: 9093
      targetPort: 9093
      nodePort: 30985

   #  Exec producer: python3 driver.py -v -p -pa AustinProducer -n 20 -t stock-market-data --bootstrap_server 100.24.242.30:30985 -r /Users/huntaj/dev/vandy/Fall2021/cs5287/cs5287progassign1/energy-data/xaa.csv -ba 1000


### END KAFKA SERVICES - DEPEND ON KAFKA BROKER DEPLOYMENTS ###

---
### COUCHDB SERVICES FOR INTERNAL AND EXTERNAL ACCESS ###
# NodePort service for accessing couchdb from public Node IP : 30984
apiVersion: v1
kind: Service
metadata:
  name: couchdb-service-external
spec:
  selector:
    app: couchdb
  type: NodePort
  ports:
    # Standard clustered port for all HTTP API requests (and web GUI)
    - protocol: TCP
      port: 5984
      targetPort: 5984
      nodePort: 30984
      name: http
---
# Internal service for couchdb reachable from within cluster
apiVersion: v1
kind: Service
metadata:
  name: couchdb-service-internal
spec:
  selector:
    app: couchdb
  type: ClusterIP
  ports:
    # Standard clustered port for all HTTP API requests (and web GUI)
    - protocol: TCP
      port: 5984
      targetPort: 5984
      name: http
    # Erlang port mapper daemon (epmd)
    - protocol: TCP
      port: 4369
      targetPort: 4369
      name: epmd
### END COUCHDB SERVICES FOR INTERNAL AND EXTERNAL ACCESS ###
---

###############################################
###############################################
############ Apache Spark Services ############
###############################################
###############################################

# CS4287-5287
# Author: Aniruddha Gokhale
# Created: Spring 2021
#
# For assignment #4
#
# This is a declarative approach to describe a Kubernetes based
# deployment of an application.  Since this is YAML, the indentation
# is very important. This is service declaration for a Spark master
#
apiVersion: v1
kind: Service
metadata:
  name: spark-master-svc
spec:
  type: NodePort   # we want this published outside so outside entities can reach it
  selector:
    app: sparkMasterApp     # used for matching
  ports:
    - name: spark-master-port   # not really needed
      protocol: TCP  # this is default
      port: 7077
      targetPort: 7077   # if not specified, is the same as port
      nodePort: 30007    # externally as 30000
    - name: spark-gui-port   # not really needed
      protocol: TCP  # this is default
      port: 8080
      targetPort: 8080   # if not specified, is the same as port
      nodePort: 30008    # externally as 30000
---
# CS4287-5287
# Author: Aniruddha Gokhale
# Created: Spring 2021
#
# For assignment #4
#
# This is a declarative approach to describe a Kubernetes based
# deployment of an application.  Since this is YAML, the indentation
# is very important. This is service declaration for a Spark driver
#
apiVersion: v1
kind: Service
metadata:
  name: spark-driver-svc
spec:
  type: ClusterIP   # published inside the cluster (default service mode)
  selector:
    app: sparkDriverApp     # used for matching
  ports:
    - name: spark-driver-port   # not really needed
      protocol: TCP  # this is default
      port: 7076     # driver listens on this port
      targetPort: 7076   # if not specified, is the same as port
    - name: spark-blkmgr-port   # not really needed
      protocol: TCP  # this is default
      port: 7079     # used by the block manager
      targetPort: 7079   # if not specified, is the same as port
    - name: spark-driver-gui   # not really needed
      protocol: TCP  # this is default
      port: 4040     # we will use this for
      targetPort: 4040   # if not specified, is the same as port

###############################################
###############################################
########## End Apache Spark Services ##########
###############################################
###############################################

