## Our consumer is the second cloud VM - this VM will be broker id 1 to form the cluster.
## Use the following tasks to update the config to use a cluster setup.
- name: Update zookeeper.connect to use VM0's Zookeeper service
  lineinfile:
    path: /home/kafka/kafka/config/server.properties
    regexp: 'zookeeper.connect=.*'
    line: "zookeeper.connect={{ hostvars['127.0.0.1'].ec2_1.instances[0].public_ip_address }}:2181"

- name: Update advertised.listeners in server.properties to use public address
  lineinfile:
    path: /home/kafka/kafka/config/server.properties
    regexp: 'advertised.listeners=.*'
    line: "advertised.listeners=PLAINTEXT://{{ hostvars['127.0.0.1'].ec2_2.instances[0].public_ip_address }}:9092"

- name: Update broker.id = 1 in server.properties
  lineinfile:
    path: /home/kafka/kafka/config/server.properties
    regexp: 'broker.id=.*'
    line: broker.id = 1