---
# https://docs.docker.com/engine/install/ubuntu/
- name: Uninstall old versions of docker
  become: yes
  remote_user: ubuntu
  apt:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: Update and upgrade apt packages
  apt:
    upgrade: "yes"
    update_cache: "yes"

- name: install necessary packages for docker installation
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add Docker’s official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg --yes

- name: set up the stable repository
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update and upgrade apt packages
  apt:
    upgrade: "yes"
    update_cache: "yes"

- name: Wait for APT Lock # resolves E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 41411 (apt-get)
  shell: while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

- name: Install Docker Engine
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
...