# Tasks to run on all cloud VMs
- name: Update and upgrade apt package index
  apt:
    upgrade: "yes"
    update_cache: "yes"
    cache_valid_time: 86400 # one day

- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - acl
    - python3-pip
    - jq

- name: Recursively change ownership /home/ubuntu to ubuntu user and group
  ansible.builtin.file:
    path: /home/ubuntu
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu

- name: Clone the GitHub repository
  remote_user: ubuntu
  become: no
  git:
    repo: https://github.com/austinjhunt/cs5287datapipeline.git
    dest: /home/ubuntu/cs5287datapipeline
    clone: yes
    update: yes
    force: yes
