# Tasks to run on all cloud VMs
- name: Update and upgrade apt package index
  apt:
    upgrade: "yes"
    update_cache: "yes"
    cache_valid_time: 86400 # one day

- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - acl
    - python3-pip

- name: Create firewall rules for Zookeeper, Kafka, and CouchDB
  become: yes
  ufw:
    rule: allow
    port: "{{ item }}"
  loop:
  - "2181"
  - "4369"
  - "5984"
  - "9092"
