---
# https://docs.docker.com/engine/install/ubuntu/
- name: Install Docker
  hosts: docker_install
  become: yes
  gather_facts: yes
  remote_user: ubuntu
  tasks:
  - name: Uninstall old versions
    apt:
      name: "{{ item }}"
      state: absent
    loop:
      - docker
      - docker-engine 
      - docker.io 
      - containerd 
      - runc
  - name: Update and upgrade apt packages
    apt:
      upgrade: "yes"
      update_cache: "yes"
      cache_valid_time: 86400 # one day
  - name: install packages
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

  # Additional Notes:
  # for the curl command, add --yes to gpg so that when rerun it will 
  # auto input yes 
  # for the echo command, from the turotial, there are some additional \ and \
  # these additional \ are causing it not set up properly. Remove these and put it in a single line 
  # to avoid unwanted issues
  # for the apt-get commnad from the tutorial, I tried to use the ansible apt, but got some errors. 
  # switch to shell for simplicity
  # when running install command, I got the following error
  # E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 41411 (apt-get)
  # found a solution at https://itsfoss.com/could-not-get-lock-error/
  - name: Add Docker’s official GPG key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg --yes
  - name: set up the stable repository
    shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  # - name: Update and upgrade apt packages
  #   apt:
  #     upgrade: "yes"
  #     update_cache: "yes"
  #     cache_valid_time: 86400 # one day
  # - name: Install Docker Engine
  #   apt:
  #     name: "{{ item }}"
  #     state: present
  #   loop:
  #     - docker-ce
  #     - docker-ce-cli
  #     - containerd.io
  - name: Update the apt package index
    shell: apt-get update
  - name: install the latest version of Docker Engine and containerd
  # add -y to auto yes
    shell: apt-get -y install docker-ce docker-ce-cli containerd.io

...