# LocalVM should clean up (stop) the cloud infrastructure now
- hosts: localvm
  remote_user: vagrant
  become: true
  gather_facts: true
  pre_tasks:
    # set up the local VM with apt packages and python requirements before doing anything else
    - name: Set up!
      import_tasks: setup-master.yml
  roles:
    - cloud-terminator

